### ISSUE TITLE
Question abt IGV & VisRSeq

### ISSUE THREAD

**Issue by CN-AlbertWu96** [hyounesy/beijing2016#2]
Hi, Pro
Nice to meet u here!
Could you tell me the relationship between IGV and VisRSeq. Why should i run both of  these two processes everytime?

**Comment by hyounesy** [comment]
VisRseq is mainly used by biologists for analysis of sequencing (genomics) data, for which IGV is used for genome visualization and genomics data reading.
The IGV dependency will be removed in the future, but for now, you may just ignore it if you are not using VisRseq for sequencing data

**Comment by CN-AlbertWu96** [comment]
Get it, thx!

**Comment by hyounesy** [comment]
you are most welcome!
