### ISSUE TITLE
Error:cannot load R

### ISSUE THREAD

**Issue by CN-AlbertWu96** [hyounesy/beijing2016#4]
Hi, i've met a problem that i cannot run apps like Boxplot which is concerned about R successfully.
I found in the cmd windows, it says cannot find path to R.

```
First connect try failed with: Cannot connect: Connection refused: connect
Windows: query registry to find where R is installed ...
ERROR: canot find path to R. Make sure reg is available and R was installed with registry settings.
Installing Rserve ...
Windows: query registry to find where R is installed ...
ERROR: canot find path to R. Make sure reg is available and R was installed with registry settings.
Cannot load R.
```

But i've installed R-3.3.1 before and is in the same catalog with VisRseq.0.9.8 in disk D.

What should i do now?  Look forward to your reply!
My OS is win10.

**Comment by hyounesy** [comment]
Hello There.
On windows, VisRseq tries to find the R installation path from the registry:

```
Path: HKEY_LOCAL_MACHINE\Software\R-core\R\
key: InstallPath
value type: REG_SZ
```

Could you please check your registry and see if this registry path and the registry key exist?
If not, are you able to try to manually create it (please do so only if you are familiar with editing registry)
Please let me know if this does not work. I will update VisRseq to allow manually specifying the R installation path.

**Comment by CN-AlbertWu96** [comment]
I've checked my registry, and make sure that in the Path ...\R-core\R\, InstallPath has existed and it points to the location where i installed R-3.3.1 accurately.

**Comment by hyounesy** [comment]
ok, thanks. I am now updating VisRseq to allow passing the R installation path through command line.
In the meanwhile, could you try running VisRseq as administrator? This should not be required, but I am wondering if it cannot read the registry key due to permission issues.

**Comment by CN-AlbertWu96** [comment]
Oh,i've tried, but it seems not work.

**Comment by hyounesy** [comment]
Ok, I have added the option to manually specify the path to R.exe. 
- Please download the new version from: https://www.dropbox.com/s/5d08qra4rsmcd3g/VisRseq.0.9.9.zip?dl=1
- extract
- edit Run_Windows.bat (preferably not in notepad as may not properly handle the line breaks)
- change the second line to:
  
  `java -Xmx4G -Drpath="Path_to_Rscript.exe" -jar VisRseq.jar`
  (replace Path_to_Rscript.exe with the full path to the Rscript.exe in your computer).
  
  Also, please make sure you have the " "  around the path if there is any spaces in the path.
  Example:

```
pushd "%~dp0"
java -Drpath="D:\Program Files\R\R-3.2.2\bin\x64\Rscript.exe" -jar VisRseq.jar
pause
```

Please give this a try. If it did not work, please send me the console log output again, as it now contains some more diagnosis information.

**Comment by CN-AlbertWu96** [comment]
Can you push this file to your github repository, so i can clone it, because i can't open the link you provided.

**Comment by hyounesy** [comment]
Since I just uploaded the file, I think it may take a little bit for the
file to be available from servers near your region. Would you please retry
downloading it again it (half an hour perhaps)?

**Comment by CN-AlbertWu96** [comment]
Ok, i will try in the morning. here is0:40 am, so i need to sleep now~ :D

**Comment by CN-AlbertWu96** [comment]
Good job! It really works!

**Comment by hyounesy** [comment]
Great! :)
