### ISSUE TITLE
Problem about R in windows

### ISSUE THREAD

**Issue by ZhangMingdong** [hyounesy/beijing2016#5]
I run in windows, and shows these:
the chinese means "there's no package named 'Rserve'", and "stop running"

Installing Rserve ...
Windows: query registry to find where R is installed ...
R InstallPath = C:\Program Files\R\R-3.3.1
Waiting for Rserve to install ... (java.lang.ProcessImpl@c33b74f)[1]
First connect try failed with: Cannot connect: Connection refused: connect
Windows: query registry to find where R is installed ...
R InstallPath = C:\Program Files\R\R-3.3.1
waiting for Rserve to start ... (java.lang.ProcessImpl@130161f7)
let us try to connect ...
Rserve>Error in library(Rserve) : 不存在叫'Rserve'这个名字的程辑包
Rserve>停止执行
Try failed with: Cannot connect: Connection refused: connect
Try failed with: Cannot connect: Connection refused: connect
Try failed with: Cannot connect: Connection refused: connect
Try failed with: Cannot connect: Connection refused: connect
Try failed with: Cannot connect: Connection refused: connect
Cannot load R.

**Comment by hyounesy** [comment]
Could you please try the suggested solution in [this thread](https://github.com/hyounesy/beijing2016/issues/4#issuecomment-232995053) ? (i.e. update to version 0.9.9 and modify the .bat file to add the full path to the Rscript.exe)

**Comment by ZhangMingdong** [comment]
It's OK now, think you.
